name: Android pull request & Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./code/gradlew
    - name: Build with Gradle
      run: ./code/gradlew build
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Give permissions
      run: chmod +x ./code/gradlew
    - name: Build debug APK
      run: bash ./code/gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: code/app/build/outputs/apk/debug/app-debug.apk
